### ISSUE TITLE
decimal degrees

### ISSUE THREAD

**Issue by zsiki** [Geo-Linux-Calculations/geofindkey#1]
it is not usual in land survaying to use decimal degrees for angles. Mostly DMS or GON units are used.
-u switch should be added to set input file angle units, for example:
-u DMS or -u GON or -u DEG

**Comment by zvezdochiot** [comment]
Not quite right. Decimal degrees are used in instruments (tacheometers:SDR33).
The orthogonal transformation in this implementation is precisely for working with instrument data.
