### ISSUE TITLE
documentationt 

### ISSUE THREAD

**Issue by zsiki** [Geo-Linux-Calculations/geofindkey#2]
It is not clear what are the difference among normal, rescale and station mode. The transformation parameters are identical all cases in the documentation.
What is in the third row (150.0025 in the demo)?
What is in the sixth row (1.000531067446 in the demo)?

The documentation should be extended.

**Comment by zvezdochiot** [comment]
Right. These points are not documented. It's just that my english is bad. Google translator only.

**Comment by zsiki** [comment]
Can I help you?

**Comment by zvezdochiot** [comment]
You have extensive experience in compiling accompanying documentation. You accompany many projects.
I have knowledge of the orthogonal transformation, experience of its application and features of its specific implementation.
If I start writing documentation from scratch, it will be very bad documentation. Useless. My English does not allow building accompanying documentation from scratch.
If there was a pattern with gaps (<...>), this would drastically change the situation.

**Comment by zvezdochiot** [comment]
Using the forums found English documentations.
