### ISSUE TITLE
Authors list?

### ISSUE THREAD

**Issue by zvezdochiot** [Geo-Linux-Calculations/geofindkey#3]
Hi @zsiki .

I added you to the source code as a co-author. I hope you don't mind?
https://github.com/Geo-Linux-Calculations/geofindkey/blob/fd31da6cb57c9c55325395d0cc63d7f7115822f0/src/geofindkey.c#L8
https://github.com/Geo-Linux-Calculations/geofindkey/blob/fd31da6cb57c9c55325395d0cc63d7f7115822f0/src/geositer500.c#L6
https://github.com/Geo-Linux-Calculations/geofindkey/blob/fd31da6cb57c9c55325395d0cc63d7f7115822f0/src/geoszbtoyxh.c#L6

**Comment by zsiki** [comment]
It is OK.
Thanks
